### ISSUE TITLE
loading Page ...

### ISSUE THREAD

**Issue by jayendrapawar** [codeTIT4N/supply-chain-truffle-react#1] opened 2022-04-28 11:55 UTC
Uploading Pharma Supply Chain - Google Chrome 2022-04-28 17-21-04.mp4…

setCurrentaccount is also set properly all things are going right but there is still setloader value is not changing

**Comment by codetit4n** [comment] 2022-04-28 12:49
Hey @JPcodebeast can you provide me some more information regarding the issue. It is not clear here

**Comment by jayendrapawar** [comment] 2022-04-28 13:02
https://user-images.githubusercontent.com/61478029/165758103-1dbdb629-486a-4a6e-8503-0b790b525920.mp4

**Comment by jayendrapawar** [comment] 2022-04-28 13:04
Video is attached. I clicked on register after local setup ....its stuck on
loading page .

**Comment by jayendrapawar** [comment] 2022-04-28 13:05
@codeTIT4N.... .whole problem is shown in video.. tell if any issue on setup done is there .... @codeTIT4N  thanks for early replies and help.

**Comment by codetit4n** [comment] 2022-04-28 19:19
Hey @JPcodebeast  I wasn't able to reproduce the issue it was working fine on my system. 

Did you install Ganache and switch your metamask network to RPC: 127.0.0.1:7545 ?

**Comment by jayendrapawar** [comment] 2022-04-29 05:57
Yes, I did that.
 Can you do one favour for me?
Just send me screen recording of local setup.

**Comment by jayendrapawar** [comment] 2022-04-29 05:57
Can we talk on call ?
****** Jayendra Pawar

**Comment by codetit4n** [comment] 2022-04-29 06:11
your email?

**Comment by jayendrapawar** [comment] 2022-04-30 05:49
***@***.***

**Comment by jayendrapawar** [comment] 2022-04-30 10:12
Reply !?

**Comment by codetit4n** [comment] 2022-05-02 03:53
can't see your mail GitHub must have hidden it. Will msg you on whatsapp

**Comment by codetit4n** [comment] 2022-05-03 17:15
since this issue was resolved i am closing it. I have hidden your number @JPcodebeast .

**Closed as completed by codetit4n** 2022-05-03 17:15 UTC

**Comment by abinashdhungana** [comment] 2022-06-23 16:28
Hello, @codeTIT4N  I'm stuck at certain point need help!!!

**Comment by jayendrapawar** [comment] 2022-06-24 04:28
What happened?

**Comment by ghost** [comment] 2023-04-25 06:15
Please what is the solution to this problem
